sudio: required
services:
  - docker

before_install:
  - docker build -t v1nc3ntl1/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true v1nc3ntl1/docker-react npm run test 

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-640307934110"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY